
version: "3.3"

services:

  # https://github.com/jenkinsci/docker/blob/master/README.md
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    # ports:
    #   - "8080:8080"
    # environment:
    #   - "JENKINS_OPTS=--prefix=/jenkins"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.entrypoints=http"
      - "traefik.http.routers.jenkins.rule=PathPrefix(`/jenkins/`)"
      - "traefik.http.routers.jenkins.service=jenkins"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-backend
      - traefik-proxy

  ssh-agent:
    image: jenkins/ssh-agent
    container_name: jenkins-ssh

volumes:
  jenkins_home:

networks:
  jenkins-backend:
    name: jenkins-backend
  traefik-proxy:
    external: true
