---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

startUrl: http://home.192.168.11.4.traefik.me/
base: http://home.192.168.11.4.traefik.me/
layout:
  composer:
    style: row
    columns: 4
showStats: true
