---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Frontend Services in Operation:
  - Homepage:
      href: http://192.168.11.2/home/
      icon: homepage.png
      description: ほーむ
      server: my-docker
      container: homepage
  - Nginx:
      href: http://192.168.11.2/
      icon: nginx.svg
      description: さーば、りばぷろ
      server: my-docker
      container: nginx
  - GitLab:
      href: http://192.168.11.2/gitlab/
      icon: gitlab.svg
      description: ぎっと
      server: my-docker
      container: gitlab
  - Redmine:
      href: http://192.168.11.2/redmine/
      icon: si-redmine-#B32024
      description: ちけっと
      server: my-docker
      container: redmine
  - Code-Server:
      href: http://192.168.11.2/coder/
      icon: code-server.png
      description: かいはつかんきょう
      server: my-docker
      container: coder
  - Jenkins:
      href: http://192.168.11.2/jenkins/
      icon: jenkins.png
      description: CICD
      server: my-docker
      container: jenkins
  - Knowledge:
      href: http://192.168.11.2/knowledge/
      # icon: mdi-crosshairs-question
      icon: https://avatars.githubusercontent.com/u/10343544?s=200&v=4
      description: なれっじ
      server: my-docker
      container: knowledge
  - Nextcloud:
      href: http://192.168.11.2/nextcloud/
      icon: nextcloud.svg
      description: すとれーじ
      server: my-docker
      container: nextcloud

- System Services in Operation:
  - Cockpit:
      href: http://192.168.11.2/cockpit/
      icon: cockpit.png
      description: サーバ監視
  - Portainer:
      href: http://192.168.11.2/portainer/
      icon: portainer.svg
      description: どっかー
      server: my-docker
      container: portainer
  - phpLDAPadmin:
      href: http://192.168.11.2/openldap/
      icon: phpldapadmin.png
      description: えるだっぷのUI
      server: my-docker
      container: openldap-ui
  - OpenLDAP:
      icon: phpldapadmin.png
      description: えるだっぷ
      server: my-docker
      container: openldap
  - Grafana:
      icon: grafana.svg
      description: さーば監視
      server: my-docker
      container: grafana
  - Prometheus:
      icon: prometheus.svg
      description: めとりくす
      server: my-docker
      container: prometheus
  - Node-Exporter:
      icon: prometheus.svg
      description: めとりくす収集
      server: my-docker
      container: node-exporter
  - cAdvisor:
      icon: cadvidor.png
      description: dockerめとりくす収集
      server: my-docker
      container: cadvidor

- Backend Services in Operation:
  - GitLab-Runner:
      icon: gitlab.svg
      description: ぎっと
      server: my-docker
      container: gitlab-runner
  - dockerproxy:
      icon: docker.svg
      description: ほーむのDockerAPI用
      server: my-docker
      container: dockerproxy
  - Jenkins-SSH-Agent:
      icon: jenkins.png
      description: CICD
      server: my-docker
      container: jenkins-ssh
  - PostgreSQL for Redmine:
      icon: postgres.svg
      description: DB
      server: my-docker
      container: redmine-db
  - PostgreSQL for Knowledge:
      icon: postgres.svg
      description: DB
      server: my-docker
      container: knowledge-db
  - MariaDB for Nextcloud:
      icon: mariadb.svg
      description: DB
      server: my-docker
      container: nextcloud-db


- Services in Experiment:
  - Open-WebUI:
      href: http://192.168.11.2:30012/
      icon: open-webui.png
      description: AIくんUI (リバプロなし)
      server: my-docker
      container: open-webui
  - Ollama:
      href: http://192.168.11.2:30012/
      icon: ollama.svg
      description: AIくん本体 (リバプロなし)
      server: my-docker
      container: ollama
  - Wiki.js:
      href: http://192.168.11.2:30010
      icon: wikijs.png
      description: なれっじ (リバプロなし)
      server: my-docker
      container: wikijs
  - PostgreSQL for Wiki.js:
      icon: postgres.svg
      description: DB
      server: my-docker
      container: wikijs-db
  - Docmost:
      href: http://192.168.11.2:30011
      icon: https://docmost.com/favicon.ico
      description: のーとていきんぐ
      server: my-docker
      container: docmost
  - PostgreSQL for Docmost:
      icon: postgres.svg
      description: DB
      server: my-docker
      container: docmost-db
  - Redis for Docmost:
      icon: redis.svg
      description: In-Memory DB
      server: my-docker
      container: docmost-redis
