concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "\"GitLab Runner\""
  url = "http://localhost/gitlab/"
  clone_url = "http://localhost/gitlab/"
  token = "JowTaMwJSyQkjexz7kG8"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
