version: "3.3"

services:

  # https://gethomepage.dev/latest/configs/docker/#using-docker-socket-proxy
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    privileged: true
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=0 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=0 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mounted as read-only
    restart: unless-stopped
    networks:
      - homepage-backend

  # https://github.com/gethomepage/homepage/
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.8.12
    container_name: homepage
    restart: unless-stopped
    privileged: true
    # ports:
    #   - 3000:3000
    environment:
      # use `id` command
      PUID: 1000
      PGID: 1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=http"
      - "traefik.http.routers.homepage.rule=HostRegexp(`home.local`)"
      - "traefik.http.routers.homepage.service=homepage"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    volumes:
      # Make sure your local config directory exists
      - ./config:/app/config
      # optional, for docker integrations
      # - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-proxy
      - homepage-backend

networks:
  homepage-backend:
    name: homepage-backend
  traefik-proxy:
    external: true
